# Server
server.port=8081

# Application
spring.application.name=user-service

# MySQL / XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/recruitment_users?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Mail (Gmail - utiliser App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:ameniguesmi0220@gmail.com}
spring.mail.password=${MAIL_PASSWORD:brck goej nluz euzt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Eureka
eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# Google OAuth
app.google.client-id=${GOOGLE_CLIENT_ID:29416346031-vnhm7i7514iptaj745aesilfpc9cfmfs.apps.googleusercontent.com}

# Frontend URL (for email verification link)
app.frontend-url=http://localhost:4200

# Upload folders
app.upload-dir=uploads/cv
app.image-upload-dir=uploads/images